set_property IOSTANDARD LVCMOS33 [get_ports {gear_button[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gear_button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gear_button[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_button[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports light]
set_property PACKAGE_PIN V1 [get_ports power_on_button]
set_property PACKAGE_PIN P4 [get_ports menu_button]
set_property PACKAGE_PIN P3 [get_ports clean_button]
set_property PACKAGE_PIN P2 [get_ports {gear_button[0]}]
set_property PACKAGE_PIN M4 [get_ports {gear_button[2]}]
set_property PACKAGE_PIN R2 [get_ports {gear_button[1]}]
set_property PACKAGE_PIN N4 [get_ports {light_button[1]}]
set_property PACKAGE_PIN R1 [get_ports {light_button[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports menu_button]
set_property IOSTANDARD LVCMOS33 [get_ports power_on_button]
set_property IOSTANDARD LVCMOS33 [get_ports clean_button]

set_property IOSTANDARD LVCMOS33 [get_ports {status[3]}]
set_property PACKAGE_PIN K1 [get_ports alert]
set_property IOSTANDARD LVCMOS33 [get_ports alert]
set_property IOSTANDARD LVCMOS33 [get_ports power_off_button]
set_property PACKAGE_PIN R11 [get_ports power_off_button]




set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN T4 [get_ports uart_tx]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_left[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_right[0]}]

set_property PACKAGE_PIN B4 [get_ports {seg_left[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_left[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_left[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_left[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_left[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_left[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_left[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_left[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg_right[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_right[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_right[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_right[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_right[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_right[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_right[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_right[0]}]
set_property PACKAGE_PIN G2 [get_ports {sel_left[3]}]
set_property PACKAGE_PIN C2 [get_ports {sel_left[2]}]
set_property PACKAGE_PIN C1 [get_ports {sel_left[1]}]
set_property PACKAGE_PIN H1 [get_ports {sel_left[0]}]
set_property PACKAGE_PIN G1 [get_ports {sel_right[3]}]
set_property PACKAGE_PIN F1 [get_ports {sel_right[2]}]
set_property PACKAGE_PIN E1 [get_ports {sel_right[1]}]
set_property PACKAGE_PIN G6 [get_ports {sel_right[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

set_property PACKAGE_PIN K5 [get_ports ps2_clk]
set_property PACKAGE_PIN L4 [get_ports ps2_data]

set_property IOSTANDARD LVCMOS33 [get_ports {debug_status[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_status[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_status[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_status[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_output_grp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports debug_light]
set_property IOSTANDARD LVCMOS33 [get_ports debug_alert]

set_property PACKAGE_PIN J2 [get_ports debug_alert]

set_property PACKAGE_PIN F6 [get_ports {debug_status[3]}]
set_property PACKAGE_PIN G4 [get_ports {debug_status[2]}]
set_property PACKAGE_PIN G3 [get_ports {debug_status[1]}]
set_property PACKAGE_PIN J4 [get_ports {debug_status[0]}]
set_property PACKAGE_PIN K2 [get_ports debug_light]


set_property IOSTANDARD LVCMOS33 [get_ports {debug_clock_state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_clock_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_clock_state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_set_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_set_state[0]}]
set_property PACKAGE_PIN K1 [get_ports {debug_clock_state[2]}]
set_property PACKAGE_PIN H6 [get_ports {debug_clock_state[1]}]
set_property PACKAGE_PIN H5 [get_ports {debug_clock_state[0]}]
set_property PACKAGE_PIN J5 [get_ports {debug_set_state[1]}]
set_property PACKAGE_PIN K6 [get_ports {debug_set_state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports debug_T]
set_property PACKAGE_PIN L1 [get_ports debug_T]
